apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- address-finder-service.yaml
- address-finder.yaml
images:
- name: victorsantoss/jarvis-address-finder-application
  newName: victorsantoss/jarvis-address-finder-application
  newTag: 1.0.0